name: FastAPI CI

on:
  push:
    branches: [ main, Py_git ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: --health-cmd "redis-cli ping" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest httpx

    - name: Run tests
      run: |
        pytest -v

    - name: Test health endpoint
      run: |
        # Запускаем сервер в фоне
        uvicorn app.main:app --host 0.0.0.0 --port 8000 &
        SERVER_PID=$!
        
        # Ждем запуска сервера
        sleep 10
        
        # Тестируем эндпоинты
        curl -f http://localhost:8000/api/v1/health
        curl -f http://localhost:8000/
        
        # Останавливаем сервер
        kill $SERVER_PID

    - name: Lint code
      run: |
        pip install black flake8
        black --check app/
        flake8 app/